apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "db.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "db.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "db.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: postgres
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.postgresUser }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.auth.postgresPassword | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.auth.database }}
        volumeMounts:
        - name: db-vol
          mountPath: /var/lib/postgresql/data
        - name: psql-pv
          mountPath: /docker-entrypoint-initdb.d
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: psql-pv
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
            - key: init.sql
              path: init.sql
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: db-vol
    spec:
      accessModes: 
        - {{ .Values.persistence.accessMode }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}